#ifndef OHT50_VERSION_H
#define OHT50_VERSION_H

#define OHT50_VERSION_MAJOR 1
#define OHT50_VERSION_MINOR 0
#define OHT50_VERSION_PATCH 0
#define OHT50_VERSION_STRING "1.0.0"

#define OHT50_BUILD_DATE __DATE__
#define OHT50_BUILD_TIME __TIME__

#endif // OHT50_VERSION_H
