# 🚨 OHT-50 Safety System Configuration
# Version: 1.0.0
# Date: 2025-09-19
# Author: FW Team
# Task: Phase 3.1 - YAML Configuration System

config_version: "1.0.0"
system_name: "OHT-50 Master Module"
config_timestamp: 1695123456789
config_author: "FW Team"

# 🌐 Global Safety Settings
global_settings:
  enable_module_monitoring: true
  enable_graduated_response: true
  enable_adaptive_polling: true
  enable_auto_recovery: true
  system_update_interval_ms: 100
  emergency_response_timeout_ms: 100
  global_safety_margin: 1.2

# 📊 Module Configurations
modules:
  # Power Module (0x02) - ESSENTIAL
  power_module:
    address: 0x02
    type: MODULE_TYPE_POWER
    is_critical: false
    timeout_ms: 5000
    safety_action: ESTOP_DELAYED
    health_check_interval_ms: 500
    max_consecutive_failures: 3
    expected_response_time_ms: 30
    max_acceptable_response_time_ms: 50
    
  # Safety Module (0x03) - SAFETY CRITICAL
  safety_module:
    address: 0x03
    type: MODULE_TYPE_SAFETY
    is_critical: true
    timeout_ms: 0
    safety_action: ESTOP_IMMEDIATE
    health_check_interval_ms: 50
    max_consecutive_failures: 1
    expected_response_time_ms: 20
    max_acceptable_response_time_ms: 50
    
  # Travel Motor Module (0x04) - IMPORTANT
  travel_module:
    address: 0x04
    type: MODULE_TYPE_TRAVEL_MOTOR
    is_critical: false
    timeout_ms: 1000
    safety_action: WARNING
    health_check_interval_ms: 1000
    max_consecutive_failures: 5
    expected_response_time_ms: 25
    max_acceptable_response_time_ms: 100
    
  # Dock Module (0x06) - OPTIONAL
  dock_module:
    address: 0x06
    type: MODULE_TYPE_DOCK
    is_critical: false
    timeout_ms: 10000
    safety_action: LOG_ONLY
    health_check_interval_ms: 5000
    max_consecutive_failures: 10
    expected_response_time_ms: 40
    max_acceptable_response_time_ms: 200

# 🔍 Critical Module Detector Configuration
detector_config:
  enable_critical_detection: true
  detection_interval_ms: 100
  max_detection_time_ms: 1000
  max_consecutive_failures: 5
  failure_rate_threshold: 0.1

# 🎛️ Graduated Response Configuration
response_config:
  enable_led_patterns: true
  enable_adaptive_polling: true
  led_update_interval_ms: 100
  polling_update_interval_ms: 1000
  transition_delay_ms: 100
  recovery_timeout_ms: 5000

# 🔧 Advanced Settings
advanced_settings:
  enable_debug_logging: false
  enable_performance_monitoring: true
  enable_statistics_collection: true
  log_buffer_size: 4096
  stats_retention_time_ms: 86400000  # 24 hours

# 💡 LED Pattern Configurations
led_patterns:
  normal:
    system_led: SOLID
    comm_led: SOLID
    network_led: SOLID
    error_led: NONE
    power_led: SOLID
    
  monitoring:
    system_led: BLINK_SLOW
    comm_led: SOLID
    network_led: SOLID
    error_led: NONE
    power_led: SOLID
    
  warning:
    system_led: SOLID
    comm_led: WARNING
    network_led: SOLID
    error_led: BLINK_SLOW
    power_led: SOLID
    
  critical:
    system_led: BLINK_FAST
    comm_led: ERROR
    network_led: BLINK_SLOW
    error_led: BLINK_FAST
    power_led: BLINK_SLOW
    
  emergency:
    system_led: ERROR
    comm_led: ERROR
    network_led: ERROR
    error_led: SOLID
    power_led: ERROR

# ⚡ Adaptive Polling Configurations
adaptive_polling:
  safety_module:
    healthy_interval_ms: 50
    degraded_interval_ms: 25
    failing_interval_ms: 10
    failed_interval_ms: 10
    offline_interval_ms: 100
    min_interval_ms: 10
    max_interval_ms: 1000
    
  power_module:
    healthy_interval_ms: 500
    degraded_interval_ms: 250
    failing_interval_ms: 100
    failed_interval_ms: 50
    offline_interval_ms: 1000
    min_interval_ms: 50
    max_interval_ms: 5000
    
  travel_module:
    healthy_interval_ms: 1000
    degraded_interval_ms: 500
    failing_interval_ms: 250
    failed_interval_ms: 100
    offline_interval_ms: 2000
    min_interval_ms: 100
    max_interval_ms: 10000
    
  dock_module:
    healthy_interval_ms: 5000
    degraded_interval_ms: 2500
    failing_interval_ms: 1000
    failed_interval_ms: 500
    offline_interval_ms: 10000
    min_interval_ms: 500
    max_interval_ms: 30000

# 🚨 Safety Action Configurations
safety_actions:
  log_only:
    description: "Log event only, no system action"
    requires_confirmation: false
    auto_recovery_enabled: true
    
  warning:
    description: "Set warning mode, continue operation"
    requires_confirmation: false
    auto_recovery_enabled: true
    
  degraded:
    description: "Degraded operation mode"
    requires_confirmation: false
    auto_recovery_enabled: true
    
  estop_delayed:
    description: "Emergency stop after delay"
    requires_confirmation: true
    auto_recovery_enabled: false
    delay_ms: 5000
    
  estop_immediate:
    description: "Immediate emergency stop"
    requires_confirmation: false
    auto_recovery_enabled: false
    delay_ms: 0

# 📊 Performance Thresholds
performance_thresholds:
  max_system_check_time_ms: 5
  max_module_check_time_ms: 1
  max_led_update_time_ms: 10
  max_config_load_time_ms: 1000
  max_config_validation_time_ms: 500
  
  # Memory limits
  max_memory_usage_kb: 1024
  max_config_file_size_kb: 64
  max_log_buffer_size_kb: 16

# 🔒 Security Settings
security_settings:
  enable_config_signing: false
  enable_config_encryption: false
  require_admin_approval: false
  config_change_audit_log: true
  max_config_changes_per_hour: 10

# 📝 Logging Configuration
logging_config:
  log_level: INFO  # DEBUG, INFO, WARNING, ERROR
  log_to_console: true
  log_to_file: true
  log_file_path: "/var/log/oht50/safety.log"
  max_log_file_size_mb: 10
  log_rotation_count: 5
  
  # Log categories
  enable_module_logs: true
  enable_safety_logs: true
  enable_performance_logs: true
  enable_config_logs: true

# 🧪 Testing Configuration
testing_config:
  enable_mock_mode: false
  mock_failure_rate: 0.05  # 5% failure rate in mock mode
  enable_hardware_simulation: false
  simulation_response_time_ms: 25
  enable_stress_testing: false
  stress_test_duration_ms: 60000
